console_title_template = '{{if .Root}} ⚡ {{end}}{{.Folder | replace "~" "🏚" }} @ {{.HostName}}'
version = 3

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '⚡ '
    foreground = '#FFEB3B'
    background = '#a313a8'
    type = 'root'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '
    foreground = '#ffffff'
    background = 'transparent'
    type = 'os'
    style = 'plain'

  [[blocks.segments]]
    leading_diamond = '<transparent,#01579B></>'
    trailing_diamond = ''
    template = ' {{ .Path }} '
    foreground = '#ffffff'
    background = '#01579B'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      folder_icon = '...'
      folder_separator_icon = '<transparent>  </>'
      home_icon = ''
      style = 'agnoster_short'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{ if .Staging.Changed }}<#FF6F00>  {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#000000'
    powerline_symbol = ''
    background = '#00C853'
    type = 'git'
    style = 'powerline'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FF{{ end }}']

    [blocks.segments.properties]
      fetch_status = true

  # [[blocks.segments]]
  #   leading_diamond = '<transparent,#49404f></>'
  #   trailing_diamond = ''
  #   template = ' {{ .FormattedMs }}s '
  #   foreground = '#ffffff'
  #   background = '#49404f'
  #   type = 'executiontime'
  #   style = 'diamond'
  #
  #   [blocks.segments.properties]
  #     style = 'dallas'
  #     threshold = 0.0

  [[blocks.segments]]
    template = '<transparent> </> {{ reason .Code }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#910000'
    type = 'status'
    style = 'powerline'

# [[blocks]]
#   type = 'prompt'
#   alignment = 'right'
#
#   [[blocks.segments]]
#     leading_diamond = ''
#     trailing_diamond = ''
#     template = '  {{ .UserName }}<transparent> / </>{{ .HostName }} '
#     foreground = '#43CCEA'
#     background = '#29315A'
#     type = 'session'
#     style = 'diamond'
#
#   [[blocks.segments]]
#     leading_diamond = ''
#     template = ' {{ .CurrentDate | date .Format }} '
#     foreground = '#3EC669'
#     background = '#29315A'
#     type = 'time'
#     style = 'diamond'
#
#     [blocks.segments.properties]
#       time_format = '15:04:05'
#
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯ '
    foreground = '#ffffff'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#ff0000{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
